./dcc < output/bad10.decaf > output/bad10.out 2>&1
./dcc < output/bad11.decaf > output/bad11.out 2>&1
./dcc < output/bad12.decaf > output/bad12.out 2>&1
./dcc < output/bad1.decaf > output/bad1.out 2>&1
./dcc < output/bad2.decaf > output/bad2.out 2>&1
./dcc < output/bad3.decaf > output/bad3.out 2>&1
./dcc < output/bad4.decaf > output/bad4.out 2>&1
./dcc < output/bad5.decaf > output/bad5.out 2>&1
./dcc < output/bad6.decaf > output/bad6.out 2>&1
./dcc < output/bad7.decaf > output/bad7.out 2>&1
./dcc < output/bad8.decaf > output/bad8.out 2>&1
./dcc < output/bad9.decaf > output/bad9.out 2>&1
./dcc < output/matrix.decaf > output/matrix.out 2>&1
./dcc < output/new.decaf > output/new.out 2>&1
./dcc < output/queue.decaf > output/queue.out 2>&1
./dcc < output/stack.decaf > output/stack.out 2>&1
./dcc < output/t10.decaf > output/t10.out 2>&1
./dcc < output/t12.decaf > output/t12.out 2>&1
./dcc < output/t13.decaf > output/t13.out 2>&1
./dcc < output/t1.decaf > output/t1.out 2>&1
./dcc < output/t2.decaf > output/t2.out 2>&1
./dcc < output/t3.decaf > output/t3.out 2>&1
./dcc < output/t4.decaf > output/t4.out 2>&1
./dcc < output/t5.decaf > output/t5.out 2>&1
./dcc < output/t6.decaf > output/t6.out 2>&1
./dcc < output/t7.decaf > output/t7.out 2>&1
./dcc < output/t9.decaf > output/t9.out 2>&1
diff -bur output/ samples/
